const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
const firstName = languages[0];
console.log(firstName);
const thirdElement = languages[2];
console.log(thirdElement);
const length = languages.length;
console.log(length);
const lastElement = languages[languages.length - 1];
console.log(lastElement);
