const number1 = 6;
const number2 = 9;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 6;
const payment = 13;
const amountRemaining = payment - charge;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 88;
const assignments = 97;
const final = 79;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Mehdi';
const lastName = ' Houasse';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 4;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 216;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
